### ISSUE TITLE
Invalid example at TransformerWrapper constructor

### ISSUE THREAD

**Issue by louis030195** [lucidrains/x-transformers#1]
In the example you use "return_logits" argument in [TransformerWrapper](https://github.com/lucidrains/x-transformers/blob/652ae8b4d6963702b1ea2d1033c2c029c56defc8/x_transformers/x_transformers.py#L402) constructor but it doesn't exist.
https://github.com/lucidrains/x-transformers/blob/652ae8b4d6963702b1ea2d1033c2c029c56defc8/examples/enwik8_simple/train.py#L43

**Comment by lucidrains** [comment]
@louis030195 ohh oops! fixed, thank you Louis!
