### ISSUE TITLE
Return Intermediates on ContinuousTransformerWrapper

### ISSUE THREAD

**Issue by gaasher** [lucidrains/x-transformers#114]
Can you create a flag that allows us to return the intermediates for the ContinuousTransformerWrapper in a similar manner to the normal transformer wrapper? This would be of great help.

**Comment by lucidrains** [comment]
@gaasher oh yea sure, try doing `return_intermediates = True` on forward and let me know if it helps

**Comment by lucidrains** [comment]
argh, accidentally checked in some experiments :face_exhaling:

**Comment by gaasher** [comment]
Thank you for the quick fix<3

**Comment by lucidrains** [comment]
just curious, but what are you using the continuous variant for?

**Comment by TKassis** [comment]
I'm using it for some continuous signal input similar to time series. Very useful! It's nice not having a fixed vocab size.

**Comment by lucidrains** [comment]
@TKassis ah very cool! i haven't come across many papers using it this way

hope you all publish some!

**Comment by gaasher** [comment]
@lucidrains, do you have any plans to work rewriting the data2vec 2.0 code? Just curious.

**Comment by lucidrains** [comment]
@gaasher no not really because isn't that already all in pytorch and open sourced?

**Comment by lucidrains** [comment]
@gaasher i am also not totally convinced about their one size fit all approach

**Comment by gaasher** [comment]
@lucidrains, their implementation of it is awful (https://github.com/facebookresearch/fairseq/tree/main/examples/data2vec). It could use some of your magic!

**Comment by lucidrains** [comment]
@gaasher haha well yea, big tech corp code is usually like that, since complexity and indirection is good for promotions

**Comment by lucidrains** [comment]
@gaasher i think it really depends on the modality you are working with. what modality are you applying transformers to?

**Comment by gaasher** [comment]
@lucidrains Vision primarily.

**Comment by lucidrains** [comment]
@gaasher highly recommend MAE then https://github.com/lucidrains/vit-pytorch#masked-autoencoder or DINO

**Comment by gaasher** [comment]
@lucidrains, I've looked into those implementations. I'm really bullish on using a student/teacher framework to learn on the latent representations themselves as opposed to using a decoder to reconstruct the actual inputs, hence why I am looking into this paper. Another similarly cool paper with this concept is MSN (https://arxiv.org/abs/2204.07141).

**Comment by lucidrains** [comment]
DINO is student teacher

**Comment by lucidrains** [comment]
oh yes, MSN is DINO-esque

**Comment by gaasher** [comment]
These strategies are DINO-esque, they just learn on the teacher/student embeddings differently. MSN uses prototypes and data2vec 2.0 uses an average of the top K FFN blocks as a target representation. Both of these strategies also use masking and various masking strategies, achieving super strong results.

**Comment by lucidrains** [comment]
ahh nice, didn't know that about data2vec

so i guess the mean teacher stuff has started to materialize

**Comment by gaasher** [comment]
Yeah, it definitely has. I know LeCunn is putting a lot of effort into it for vision at the moment. He's put a number of papers on joint embedding learning recently but https://arxiv.org/abs/2206.07700 is one of his bigger ones. 
Also, the new data2vec paper is hard to read (it came out yesterday but isn't on arxiv), here it is if you want to take a look. You might find it cool:
https://scontent.ford4-1.fna.fbcdn.net/v/t39.2365-6/319548823_683029250213299_1077720056858201599_n.pdf?_nc_cat=110&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=9w_5s2HIfBkAX9q-Tae&_nc_ht=scontent.ford4-1.fna&oh=00_AfDQAbn5Nu9lh_AkX_Q77MsfikjLs-XpdHoUrpLm3gNLiA&oe=639E419A

**Comment by gaasher** [comment]
He presented on it too at NeurIPS if I remember correctly.

**Comment by lucidrains** [comment]
@gaasher saved it for future reading, thanks! yea, i wasn't too impressed with data2vec 1.0, but wasn't aware of the more recent version (2.0?)

**Comment by lucidrains** [comment]
will definitely have to get caught up on the latest with SSL, too many things happening all at once

**Comment by gaasher** [comment]
@lucidrains I also wasn't that impressed with 1.0. But the 2.0 version seems much more impressive. Especially when you consider the massive speedups compared to MAE and normal MIM methods.

**Comment by lucidrains** [comment]
@gaasher thank you for sharing this! you convinced me to sit down and read the paper this weekend. i'm quite out of the loop

code, run experiments, read papers, choose 2 😆

**Comment by gaasher** [comment]
@lucidrains thank you, and thank you for your work! Your code is a life saver.
