### ISSUE TITLE
ff_no_bias is missing compared to readme

### ISSUE THREAD

**Issue by mistycube** [lucidrains/x-transformers#120]
Hello @lucidrains,
I think the flag ff_no_bias is missing compared to readme.

**Comment by lucidrains** [comment]
@mistycube hey! it should be there https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L547 the `ff_` automatically forwards the keyword arguments to the feedforward modules https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L879

**Comment by mistycube** [comment]
oh great. thanks. Awesome repo :). I will close the issue now
