### ISSUE TITLE
Transformer for regression/time series

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [lucidrains/x-transformers#121]
Hey guys, thanks for building such a nice GitHub repo. I am working on a problem where I am having tabular data having more than 90 features and one target and all the features are in integers (continuous). I want to use pre-trained BERT, GPT2 but when it comes to the tokenizer the tokenizer is expecting the input in the text format. I can change the integer data in the text format like this;

    original_data = [1,2,3,4,5,…,94]
    transformed_data = [“1 2 3 4 5 …94”]

Now if I pass the transformed_data to the tokenizer then surely it will work but I wanna know if someone tried to use transformers for this purpose and if yes, then what was the outcome, and how did the results look like?

How can I use huggingface transformer library for this purpose all the tokenizers are trained for the text data so I am kinda lost. Any help will be appreciated. Thanks

**Comment by lucidrains** [comment]
@HasnainKhanNiazi i think the latest paper i saw was https://arxiv.org/abs/2211.14730

**Comment by HasnainKhanNiazi** [comment]
@lucidrains thanks for your answer, I read the paper but the problem with the paper is that they are using the autoregressive decoder where the input of the decoder is always having the `y` values in the input which needs to be predicted but in my case, I don't want to pass the true values as in production, I will not be having `y` values so I padded the `y` values with zero in inference but results don't look promising. That's why I wanted to use pre-trained models for this problem.

**Comment by lucidrains** [comment]
@HasnainKhanNiazi yea, i would say just stick with xgboost, especially if you have a looming deadline and need guaranteed results

making transformers work well for tabular and time series data is still an ongoing research problem

**Comment by HasnainKhanNiazi** [comment]
@lucidrains thanks for your useful suggestions. There isn't any tight deadline that's why I am doing experiments with Transformers. I am closing this issue but if anyone else tried to use Transformer for this purpose then please do comment. Thanks
