### ISSUE TITLE
BERT Training and Word-Level Tokenization

### ISSUE THREAD

**Issue by XiaoWang-Github** [lucidrains/x-transformers#129]
Hi Phil,

I am not sure how to use your x-transformer code for BERT training. Is it possible for you to share an example training script that can train on a BERT standard benchmark dataset? More specifically, I don't know how to use your code for word-level or sub-word tokenization, such as WordPiece, instead of characters-level tokenization. It doesn't seem like your project has this feature. In addition, if I have a list of vocabularies, how do I import this vocab list to your code for token embedding?

**Comment by lucidrains** [comment]
@XiaoWang-Github hi Xiao, i recommend checking out [this repository](https://github.com/lucidrains/mlm-pytorch)

[this one as well](https://github.com/lucidrains/electra-pytorch)
