### ISSUE TITLE
Importing AttentionLayers

### ISSUE THREAD

**Issue by hadaev8** [lucidrains/x-transformers#13]
I want to have two encoders (not seq2seq) and seems like i cant use default abstractions.
Would be nice to be able to import AttentionLayers class from lib.

**Comment by lucidrains** [comment]
@hadaev8 Hello again! You can import the attention layers as `Encoder` or `Decoder` depending

Is that not good enough for your use-case?

**Comment by hadaev8** [comment]
Oh, sorry, didnt realized i should pass cross attn param to encoder class.
