### ISSUE TITLE
Cross attention between different shape tensors

### ISSUE THREAD

**Issue by Hosein47** [lucidrains/x-transformers#134]
Is it possible (in a meaningful way) to do a cross attention between these two tensors: x with size [15,100,32] and context vector with size [15, 32]. I want the attention to happen between the 15 elements such that the attention matrix would have the size [15,15], and the output to be again of the size of x?

**Comment by lucidrains** [comment]
@Hosein47 what is dimension for `100` though?

**Comment by Hosein47** [comment]
How should I expand it? since the vector is only [15,32].
The dimension 100 is the sequence length but I want the attention to happen between elements of the mini-batch which is 15. Thus, in the language of the cross-attention the seq=15 then.

**Comment by lucidrains** [comment]
@Hosein47 what is the use-case here? are you doing some sort of contrastive learning?

**Comment by lucidrains** [comment]
@Hosein47 in that case, `100` would be your batch, and your batch would be the sequence length

reorder your first tensor to be `[100, 15, 32]`, then expand your second to be the same by `unsqueeze(0).expand(100, -1, -1)`
