### ISSUE TITLE
Suggestion for OOD extrapolation power of Transformers

### ISSUE THREAD

**Issue by Hosein47** [lucidrains/x-transformers#135]
Hi @lucidrains,
I am working on a task that requires the layers (transformer encoder and decoder) to generalise and extrapolate well to OOD data (with mostly the same sequence length but different correlation profile). I wonder what are some suggestions and recommendations to follows while using the encoder and decoder layers. I already use emb_dropout 0.1 and rotary_pos_emb.

**Comment by lucidrains** [comment]
@Hosein47 what you are looking for won't be solved with some hyperparameter changes to the transformer

**Comment by Hosein47** [comment]
@lucidrains So, one cannot do "Context Extrapolation" with Transformer family of models given a conditional prior?

**Comment by lucidrains** [comment]
@Hosein47 what papers are you reading that suggest this is possible?

**Comment by lucidrains** [comment]
@Hosein47 you figure out a way for transformers to extrapolate, or any system to reliably extrapolate, you'll be a famous man.

**Comment by lucidrains** [comment]
ok sounds good, i'll reply later this evening, got some work to finish
