### ISSUE TITLE
Feature request: use scaled_dot_product_attention()

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/x-transformers#136]
It would be great if this repo used `torch.nn.functional.scaled_dot_product_attention()` where possible to minimize memory consumption and optimize speed.

**Comment by lucidrains** [comment]
yes, that is in my plans!

**Comment by pfeatherstone** [comment]
Awesome! I really struggle to use transformers practically. They are impossible to train on even a couple of 12GB cards.

**Comment by lucidrains** [comment]
haha yea, transformers are a beast to train

rewards are obviously great if you can do it though

**Comment by pfeatherstone** [comment]
I think we need more transformer primitives that are end-to-end defined in either c++ or cuda to really minimise memory as much as possible.

**Comment by lucidrains** [comment]
@pfeatherstone ok it is done! https://github.com/lucidrains/x-transformers#flash-attention

**Comment by pfeatherstone** [comment]
Nice I'll give it a go
