### ISSUE TITLE
Feature request for customizing inner dim of ff module

### ISSUE THREAD

**Issue by hadaev8** [lucidrains/x-transformers#14]
Hello again!
In this paper they use self attention dim 1024 and ff dim 768
https://arxiv.org/pdf/2010.10499.pdf

**Comment by lucidrains** [comment]
@hadaev8 it isn't documented, but you can actually control all the keyword arguments going into the feedforward class by prepending `ff_` then the keyword name

so for feedforward inner dimension, you do `ff_mult = int(768 / model_dim)`

**Comment by hadaev8** [comment]
This would not work.
int(768 / 1024)

**Comment by lucidrains** [comment]
@hadaev8 pass in (768 / 1024) in the latest version, it now accepts floats smaller than 1!

**Comment by hadaev8** [comment]
@lucidrains thanks.
Any reasons to have inner attention dim 512 and dropout 0?

**Comment by lucidrains** [comment]
@hadaev8 most of the larger attention nets have been starting to remove dropout. their utility may be diminished as we approach large data and model sizes

the inner attention dimension can be adjusted with the dimension per head, which is best kept at 64, and at most 128. you can scale the number of heads, the framework should keep the dimension of head constant, which is how it aught to be

**Comment by lucidrains** [comment]
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/released_checkpoints.md#first-layers-narrow-t51n4w10 5.1.1
