### ISSUE TITLE
Enhanced recurrence question

### ISSUE THREAD

**Issue by danieltudosiu** [lucidrains/x-transformers#142]
Hi Lucidrains,

Thank you for the fantastic work you keep doing with your open-source projects.

I am using your library for a generative modelling project and I have a question regarding the Enhanced recurrence feature controlled by the shift_mem_down parameter. 

I have set the parameter to 1 but I did not set return_mems to True nor did I pass mems like in the example you have [here](https://github.com/lucidrains/x-transformers/tree/0.25.4#enhanced-recurrence) (yes the link is on purpose to 0.25.4 version as is the one I used).

Even if I did not use those, I obtained substantial improvement in my FID and better MMD and diversity as measured by MS-SSIM. Is there any way that parameter could influence the training of the model?

From my understanding, this should not be possible since the model would just ignore the parameter without mems passed. Am I right?

Cheers,

Dan

**Comment by lucidrains** [comment]
@danieltudosiu hey Dan! thanks for the kind words. yea, it shouldn't do anything if you aren't passing the memories back

**Comment by lucidrains** [comment]
oh, are you using the `XLAutoregressiveWrapper`?

**Comment by danieltudosiu** [comment]
Hi Lucidrains, 

No, I am not using the `XLAutoregressiveWrapper` so it won't have any effect. 

Thanks!

**Comment by lucidrains** [comment]
@danieltudosiu hope you are able to replicate it, especially if those results are SOTA lol
