### ISSUE TITLE
Question: clarification of ResiDual implementation

### ISSUE THREAD

**Issue by alstonlo** [lucidrains/x-transformers#145]
From my understanding of the ResiDual paper, shouldn't [L1143-1144](https://github.com/lucidrains/x-transformers/blob/52bcac25437064757d8c4e5bd9e77b9598b462bb/x_transformers/x_transformers.py#L1143):  
```python
 x = x + pre_norm(outer_residual)
```
be positioned outside of the for loop (so that it only occurs once at the end of the forward pass). Apologies in advance if this is a misunderstanding on my end!

**Comment by lucidrains** [comment]
@alstonlo :man_facepalming: yes, i totally misconstrued the diagram

thank you for pointing this out! do you want to do a quick [code review](https://github.com/lucidrains/x-transformers/commit/aa3ffc811e67bdb4faca196f3dde32bb2fcb8b46) ?

**Comment by alstonlo** [comment]
LGTM, thanks!

**Comment by lucidrains** [comment]
@alstonlo i'm kind of curious now if the way i did it would make a difference

**Comment by lucidrains** [comment]
haha yes! I'm sure not as performant, given extra normalization and linear per layer

maybe you can write the follow up paper 😅

**Comment by zippeurfou** [comment]
If it helps microsoft has an official implementation:
https://github.com/microsoft/ResiDual/blob/main/resi_dual/resi_dual.py
Maybe it would make sense to write it in plain first to see if it follows the same logic.
ie. postnorm = ln(x+mha(x))
