### ISSUE TITLE
Feature request for adding Memformer memory

### ISSUE THREAD

**Issue by mistycube** [lucidrains/x-transformers#15]
So i've checked the memformer repository and this one. I think it would be good to add the memory from the memformer to this project also since it seems more general and better than the transformer XL memory.

**Comment by lucidrains** [comment]
Wow, this request is a bit from the left field

Have you used the memory module from the memformer paper with any success?

**Comment by mistycube** [comment]
I would like to test it within this framework. I read the paper and seems to me superior and efficient than the memory from transformer XL ( https://arxiv.org/pdf/2010.06891.pdf ). Also works with the same relative position encoding used in this project. I think the only complicated part would be to port and have a parameter to enable or disable the memory cross attention module but my guess it should be feasible with everything else.

**Comment by lucidrains** [comment]
@mistycube if you can show me clear data that memformer performs better on some task, I will consider integrating it

**Comment by lucidrains** [comment]
@mistycube interesting that the paper is not getting accepted https://openreview.net/forum?id=_adSMszz_g9

**Comment by mistycube** [comment]
Ok i didn't see the review. I will play with it and let you know if it I find any good results. I will close this now. thanks

**Comment by lucidrains** [comment]
@mistycube let me know in the memformer repo what kind of results you get! another researcher has reported good results https://github.com/lucidrains/memformer/pull/1

**Comment by mistycube** [comment]
Another recent paper by researchers from Facebook https://arxiv.org/pdf/2002.09402.pdf also commented by 
Yannic Kilcher here https://www.youtube.com/watch?v=zdb8MM94A5c&ab_channel=YannicKilcher. Very similar to memformer with more experimentation and results

**Comment by lucidrains** [comment]
@mistycube try it out here! https://github.com/lucidrains/feedback-transformer-pytorch
