### ISSUE TITLE
AlibiPositionalBias: slicing buffered bias

### ISSUE THREAD

**Issue by antony-frolov** [lucidrains/x-transformers#152]
https://github.com/lucidrains/x-transformers/blame/b4756498b307b0f173e329312f79f698315d595d/x_transformers/x_transformers.py#LL361C59-L361C59

Hi! Shouldn't we check here the dimensions for both i and j?

**Comment by lucidrains** [comment]
@antony-frolov hey Antony! you are right, it should have an extra check on the other dimension as well
