### ISSUE TITLE
Any plans to implement the new flash sparsed attention?

### ISSUE THREAD

**Issue by kyegomez** [lucidrains/x-transformers#155]
https://github.com/epfml/dynamic-sparse-flash-attention/blob/main/runtime-experiments/timeperf-hash-and-qk-sparse.ipynb

**Comment by lucidrains** [comment]
yea I saw, but not too excited about the paper (yet) unless if someone changes my mind

**Comment by kyegomez** [comment]
They demonstrate an iteration of flash attention that can process 32,000 input tokens at sub 100 milliseconds, is this bad?

**Comment by lucidrains** [comment]
i would say it is an incremental improvement to reformer, but not enough to be usable just yet

**Comment by lucidrains** [comment]
numbers are meaningless without language modeling results

**Comment by kyegomez** [comment]
Why is it not usable enough? What defines usable?
