### ISSUE TITLE
LoRA fine-tuning? 

### ISSUE THREAD

**Issue by hugofloresgarcia** [lucidrains/x-transformers#158]
Hi! How could I go about adapting this library so that it supports finetuning with LoRA?

**Comment by lucidrains** [comment]
@hugofloresgarcia i think its a bit outside the scope of the project, but you should follow the example set forth in [this repository](https://github.com/lucidrains/PaLM-rlhf-pytorch/blob/main/palm_rlhf_pytorch/lora.py)

**Comment by hugofloresgarcia** [comment]
thanks!
