### ISSUE TITLE
ContinuousTransformerWrapper returning list of tensors as opposed to stack of tensors in 1.16.20

### ISSUE THREAD

**Issue by gaasher** [lucidrains/x-transformers#167]
When working with your most recent implementation of x-transformers (1.16.20) there is an error with ContinuousTransformerWrapper. The output of this module was a list of tensors as opposed to a stacked tensor. Therefore I would be outputted with a list as follows (Tensor1,  Tensor2, etc...) as opposed to Tensor([Tensor1, Tensor2, etc....]).

**Comment by lucidrains** [comment]
oops! fixed in 1.6.21 lol 🤣
