### ISSUE TITLE
Is there a plan to handle the inference slowness？ eg. KV Cache

### ISSUE THREAD

**Issue by liuzhuang1024** [lucidrains/x-transformers#170]

**Comment by lucidrains** [comment]
oh yup, can add this

was going to play around with speculative and contrastive decoding soon too

**Comment by lucidrains** [comment]
unless if you want to give it a shot with a PR

**Comment by liuzhuang1024** [comment]
> unless if you want to give it a shot with a PR

Maybe, when I have free time.

**Comment by lucidrains** [comment]
k no prob, should be able to get this done by this week's end, and play around with speculative decoding too

**Comment by lucidrains** [comment]
@liuzhuang1024 hey, started playing around with spec decoding, and decided to circle back to this issue https://github.com/lucidrains/x-transformers/commit/87a0f13d7730869d1e3b4af384f6813e08fd0021 let me know if it works ok

**Comment by lucidrains** [comment]
also, if anyone knows any paper with interesting (and unimplemented) ideas for speeding up causal transformer sampling, do share it now while my attention is on this

**Comment by LouChao98** [comment]
Some paper propose to prune kv cache to speed up long sequence generation, based on attention scores received in the history.

https://arxiv.org/abs/2306.14048

https://arxiv.org/abs/2305.17118

**Comment by lucidrains** [comment]
@LouChao98 ah nice, but i don't know if i believe in that route

**Comment by lucidrains** [comment]
i'll give you a contrived example. the attention network is looking at some code and there is an earlier parenthesis. it would discard that early parenthesis because it is trying to attend to the logic of the inner scope. later on, it needs to balance that early parenthesis, and that token would be discarded. just a quick thought experiment and you'd realize it would fail

**Comment by lucidrains** [comment]
i think this should be completed

i'll get around to some savings with absolute positional embedding at a later date
