### ISSUE TITLE
Question: normalizing mask shape

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/x-transformers#172]
When we pass a mask with shape [B,L], the code basically either does:
```
mask = rearrange(mask, 'b i -> b 1 i 1')
```
or 
```
mask = repeat(mask, 'b i -> b h i j', h=heads, j=mask.shape[1])
```
Shouldn't it be:
```
mask = rearrange(mask, 'b i -> b 1 i 1') & rearrange(mask, 'b i -> b 1 1 i')
```
or
```
mask = repeat(mask, 'b i -> b h i 1', h=heads) & rearrange(mask, 'b i -> b 1 1 i')
```
?

Otherwise items can attend to padded items no ?

**Comment by lucidrains** [comment]
@pfeatherstone if you find `mask = rearrange(mask, 'b i -> b 1 i 1')` in the code, it is likely an error

**Comment by pfeatherstone** [comment]
Thanks. I have more than likely done that in the past.
