### ISSUE TITLE
Dimension mismatch with cross attention

### ISSUE THREAD

**Issue by pradeep-pyro** [lucidrains/x-transformers#174]
When using cross-attention in v1.17.1, I encountered an error in `attend.py` line 269 that the dimension of the mask does not match with the dimension of the context. Seems like a new issue as it works ok in v1.14. Thanks!

**Comment by lucidrains** [comment]
@pradeep-pyro oh i see! thank you for reporting this! so the `mask` actually shouldn't matter at all

in cross attending, `context_mask` is used instead

fixed the erroneous logic and it should run now in 1.17.2

**Comment by pradeep-pyro** [comment]
That makes sense, thanks for the quick fix!
