### ISSUE TITLE
Do you consider adding retnet

### ISSUE THREAD

**Issue by chaodreaming** [lucidrains/x-transformers#176]

**Comment by lucidrains** [comment]
someone else had already started an implementation. do a search on github

**Comment by lucidrains** [comment]
I don't really believe that paper, until someone replicates it in the wild

**Comment by chaodreaming** [comment]
I'm not talking about implementing retnet. The official source code is already open, but I'm talking about adding it to x_ In the Transformers decoder

**Comment by lucidrains** [comment]
ah, even if the paper does pan out, I probably won't build out any of it here. It is too different

**Comment by lucidrains** [comment]
that said, if some groups scales it and it survives scrutiny, do let me know

**Comment by chaodreaming** [comment]
Does it mean that the paper is accepted by the journal

**Comment by lucidrains** [comment]
not necessarily. some group just has to train a bigger one on red pajamas and prompt around, see if there are any clear deficiencies.

**Comment by lucidrains** [comment]
the other thing I'm watching for is rwkv5, which is supposedly incorporating some learning points from retnet. What I'm looking for is their fixing the prompting issue. check out limitations section in rwkv paper

**Comment by chaodreaming** [comment]
I'm just looking forward to someone who can train and reason quickly, and the context 2k is enough

**Comment by lucidrains** [comment]
sg, let's wait and see, now that the official code is out

**Comment by chaodreaming** [comment]
be waiting to see

**Comment by chaodreaming** [comment]
https://arxiv.org/pdf/2309.11523.pdf

**Comment by chaodreaming** [comment]
@lucidrains

**Comment by lucidrains** [comment]
@chaodreaming that's for vision though

I've been chatting with some folks, and nobody was able to scale retnet successfully.

**Comment by chaodreaming** [comment]
ok
