### ISSUE TITLE
return hidden states of all layers

### ISSUE THREAD

**Issue by zhiaos** [lucidrains/x-transformers#177]
For Bert like model:

```python
model = TransformerWrapper(
    num_tokens = 20000,
    max_seq_len = 1024,
    attn_layers = Decoder(
        dim = 512,
        depth = 12,
        heads = 8
    )
).cuda()
```

Is it possible to return hidden states from all layers similar to Huggingface BertModel when setting `output_hidden_states=True`  [(Huggingface)](https://github.com/huggingface/transformers/issues/1827#issuecomment-554028292). 

I tried
```python
x = torch.randint(0, 256, (1, 1024)).cuda()
logit, intermediates = model(x, return_intermediates=True)
```

But I believe `intermediates.hiddens` is not exactly the hidden states for each layer.

**Comment by lucidrains** [comment]
what is the hidden states by their definition? is it the input going into each transformer block? (or each attention / feedforward block) ?

**Comment by lucidrains** [comment]
```python
import torch
from x_transformers import TransformerWrapper, Decoder

model = TransformerWrapper(
    num_tokens = 20000,
    max_seq_len = 1024,
    attn_layers = Decoder(
        dim = 512,
        depth = 12,
        heads = 8
    )
)

x = torch.randint(0, 256, (1, 1024))

x, intermediates = model(x, return_intermediates = True) # (1, 1024, 20000)

intermediates.layer_hiddens # length 25 - 24 blocks (attention, feedforward alternating) + output of last block
```

**Comment by lucidrains** [comment]
@zhiaos let me know if `layer_hiddens` has what you need

i can clean up the naming at a later version

**Comment by zhiaos** [comment]
Thanks @lucidrains!  

Based on their documentation,  hidden states represent the outputs of each layer  -- 12 * (Attention+Residual&Norm + FF + Residual&Norm) . So there are 12 of them.  I think the `layer_hiddens` returns 12 *[ Attention+Residual&Norm,  FF+Residual&Norm] + x,   x is the same as the last of 24 in typical case.

**Comment by lucidrains** [comment]
@zhiaos got it, yea, i need to return after each block, since this framework supports arbitrary ordering of attention and feedforwards (say `a f f a f f`)

**Comment by zhiaos** [comment]
@lucidrains  so it is not possible to get the output of each block based on current implementation?

**Comment by lucidrains** [comment]
@zhiaos the outputs before the prenorm residual is added? are you sure that's what you want?

**Comment by lucidrains** [comment]
@zhiaos the `layer_hiddens` are the inputs to each block, which should be the output of the previous block (+ residual)
