### ISSUE TITLE
Learned memory keyword change

### ISSUE THREAD

**Issue by cfoster0** [lucidrains/x-transformers#18]
I believe an earlier version may have used `attn_num_mem_kv` as the keyword argument for setting how many persistent memory vectors should be used. It looks like this is now `num_mem_kv`. The example in the readme has the older form.

**Comment by lucidrains** [comment]
@cfoster0 Hey Charles! It's still the same, but I think I know why it may appear to be `num_mem_kv`

While it is `num_mem_kv` as a keyword argument to the attention class, it is actually defined on the attention layers class, with this magic https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L421 that prefixes the keyword with 'attn_' and passes it into the Attention class
