### ISSUE TITLE
Questions on rotary position embedding

### ISSUE THREAD

**Issue by LouChao98** [lucidrains/x-transformers#182]
https://github.com/lucidrains/x-transformers/blob/612632d22c6856f1305399e1a6e140813dbd1084/x_transformers/x_transformers.py#L813-L817

In x-transformer, rotary position embedding will rotate v. I think this is different from others implementation. Is there a specific reason to rotate v?

**Comment by lucidrains** [comment]
@LouChao98 hey, thank you for catching this

i removed the rotating of values from 1.20.0

the back story is that rotary embeddings was added to this repository at a time when the paper was not even released, when the technique was being passed around NLP circles in Beijing, and while a bunch of open source folks on the eleuther discord were investigating the technique. i had been running experiments on a [toy task](https://github.com/lucidrains/x-transformers/blob/main/examples/toy_tasks/enc_dec_copy.py), which relies on both absolute and relative positions to work well. however, learned absolute positions didn't mix well with rotary embeddings in my experiments. the author of rotary embeddings popped up on the discord and proposed rotating the values as a means of introducing absolute positions (in addition to relative), and that fixed it. once the roformer paper became official and the technique took off, i failed to remove it
