### ISSUE TITLE
Support for flash attention 2

### ISSUE THREAD

**Issue by andrecornman** [lucidrains/x-transformers#186]
Hi @lucidrains,

Thanks for developing and maintaining this great repo! Do you have any plans to support flash attention 2? 

Also I noticed that flash attention is currently enabled only for A100 here: https://github.com/lucidrains/x-transformers/blob/main/x_transformers/attend.py#L132
Could this be changed to support H100?

**Comment by lucidrains** [comment]
@andrecornman hey no problem

i believe the pytorch team has plans to integrate flash attention 2 into pytorch core

**Comment by lucidrains** [comment]
@andrecornman yea sure, just get me the correct device major and minor and i'll add it

**Comment by andrecornman** [comment]
@lucidrains Thanks a lot! `torch.cuda.get_device_properties()` returns `_CudaDeviceProperties(name='NVIDIA H100 PCIe', major=9, minor=0, total_memory=81008MB, multi_processor_count=114)`

**Comment by lucidrains** [comment]
@andrecornman ok, try 1.22.7

**Comment by s-rog** [comment]
`name='NVIDIA GeForce RTX 4090', major=8, minor=9, total_memory=24563MB, multi_processor_count=128`

Can 4090s be added too?

**Comment by lucidrains** [comment]
@s-rog yup added

**Comment by s-rog** [comment]
@lucidrains Thanks so much!

**Comment by chaodreaming** [comment]
Why not support 4090
