### ISSUE TITLE
Issue with qk scale between flash attention and normal attention when qk_norm is True

### ISSUE THREAD

**Issue by mistycube** [lucidrains/x-transformers#190]
When qk_norm is True :
In flash attention the scale is calculated as follow:
if self.qk_norm:
            default_scale = q.shape[-1] ** -0.5
            q = q * (default_scale / self.scale)

In normal attention it is as follow:
scale = default(self.scale, q.shape[-1] ** -0.5)
dots = einsum(f'b h i d, {kv_einsum_eq} -> b h i j', q, k) * scale

It seems to me that when qk_norm is True, the default value of scale is 10 and in Flash attention we divide the dots by 10√ d but in normal attention we multiply the dots by 10 instead.

**Comment by lucidrains** [comment]
@mistycube thank you for pointing this out! this is indeed an issue with qk norm + flash attention combination and should be fixed

**Comment by lucidrains** [comment]
ideally one should be able to specify a custom scale though, for a variety of scenarios (muP, Su's log(seqlen) scaling, etc)
