### ISSUE TITLE
pre_norm_has_final_norm kwarg not used

### ISSUE THREAD

**Issue by sashakunitsyn** [lucidrains/x-transformers#202]
Not sure if this is a bug or a feature, but this kwarg https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L985 is set but never used.  Maybe it should be used here as additional condition https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L1137?

**Comment by lucidrains** [comment]
@sashakunitsyn oh yes, i was initially using that when dealing with `ResiDual` paper, which had an exotic pre + post-norm combination

removed it for clarity! thank you!
