### ISSUE TITLE
Using Rotary Positional Encoding with Continuous Wrapper

### ISSUE THREAD

**Issue by anthonyzhou-1** [lucidrains/x-transformers#203]
There seems to be an error in importing the class 'always' when using RoPE with the continuous wrapper: 
```
        if not (use_abs_pos_emb and not attn_layers.has_pos_emb):
            self.pos_emb = always(0)
```

Importing 'always' from x_transformers.py seems to fix it.

**Comment by lucidrains** [comment]
oh yes, my bad

want to submit a PR? I'm in transit
