### ISSUE TITLE
Question: return_mems and rotary_pos_emb

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/x-transformers#205]
In the documentation, it says "making sure your Decoder has `rel_pos_bias` set to `True`.
If you use `rotary_pos_emb = True` it works but is it actually going to do the right thing on the next iteration?

So is:
```
import torch
from x_transformers import TransformerWrapper, Decoder

model_xl = TransformerWrapper(
    num_tokens = 20000,
    max_seq_len = 512,
    max_mem_len = 2048,
    attn_layers = Decoder(
        dim = 512,
        depth = 6,
        heads = 8,
        rotary_pos_emb = True
    )
)

seg1 = torch.randint(0, 20000, (1, 512))
seg2 = torch.randint(0, 20000, (1, 512))
seg3 = torch.randint(0, 20000, (1, 512))

logits1, mems1  = model_xl(seg1, return_mems = True)
logits2, mems2  = model_xl(seg2, mems = mems1, return_mems = True)
logits3, mems3  = model_xl(seg3, mems = mems2, return_mems = True)
```

well defined ?

**Comment by pfeatherstone** [comment]
the reason why i want to use `rotary_pos_emb` is mainly so i can use flash attention. But also because it claims to be better than relative positional bias.

**Comment by lucidrains** [comment]
@pfeatherstone yup! rotary positions are compatible with transformer-xl

**Comment by pfeatherstone** [comment]
@lucidrains Thank you! Just wanted to check. Wasn't sure if there would be a discontinuity in the embeddings when routing `mems` to the next iteration

**Comment by pfeatherstone** [comment]
Maybe we could update the docs to say "making sure your Decoder has `rel_pos_bias` or `rotary_pos_emb` set to `True`"
