### ISSUE TITLE
Question: How to load model trained on earlier version of x-transformers

### ISSUE THREAD

**Issue by tmphex** [lucidrains/x-transformers#221]
I appreciate the effort you are putting @lucidrains in keeping this library up to date with new advancement in the fields. But often when a model has been trained with older version and if I try to load it with latest version if fails for one or other reason. Wondering what is the best practice here to handle such situations and enable users to use the latest version but still load and run models trained on earlier versions of this library.

**Comment by lucidrains** [comment]
@tmphex you need to [pin](https://discuss.python.org/t/how-to-pin-a-package-to-a-specific-major-version-or-lower/17077) the version you are using

**Comment by lucidrains** [comment]
otherwise, it is fine to just copy and paste the entire file or two and pare down to what you need. i design my repositories to be such a way. there's no other choice in such a fast moving field

**Comment by tmphex** [comment]
Yeah I have been staying on older version `0.28.4` but seeing lot of new enhancements, I wanted to upgrade my version but then I can not load up my old trained models.

I was thinking the same as to cherry-pick features from your repo and have my own code which is more stable. But I was hoping that I don't need to do and some smart people here can suggest some other better approach ;)

**Comment by lucidrains** [comment]
@tmphex yea, that's just the product of being on the bleeding edge of research
