### ISSUE TITLE
Enhancement: Multi Input/Output transformers

### ISSUE THREAD

**Issue by RyanKim17920** [lucidrains/x-transformers#222]
Hey @lucidrains, while working with your x-transformers for a music transformer, I found the need to incorporate multiple input/output modifications into the code. If I adapt this code to handle various inputs/outputs, would you be open to me submitting a pull request? I'm thinking of either modifying the existing TransformerWrapper and AutoRegressiveWrapper or creating a new version, perhaps named MultiIOTransformerWrapper/MultiIOAutoRegressiveWrapper. What do you think?

**Comment by lucidrains** [comment]
yea definitely! they could live in a separate file, like continuous or xval
