### ISSUE TITLE
Removed biases breaks pre-trained models

### ISSUE THREAD

**Issue by zqevans** [lucidrains/x-transformers#225]
The recent change to remove biases across the model means I can't load my previously-trained x-transformers models.

It would be nice if the previous behavior were the default to remain backwards-compatible, with an option to remove all of the biases

**Comment by lucidrains** [comment]
@zqevans ah, i bumped a minor version though

can't you just pin it?

**Comment by lucidrains** [comment]
it had to happen at some point. layernorm biases were shown to make transformer training unstable

**Comment by zqevans** [comment]
I can pin it, it just means the stable-audio-tools library can't start using any features past that point since it's pinned.

Could you at least make them opt-in? That way the default is still the ideal setup, and newer models get that automatically, but old ones can still be used with the right settings turned on.

**Comment by lucidrains** [comment]
@zqevans yea, i think that would overly complicate the repo for little gain

why not just anneal out the biases over an extra epoch of training?

**Comment by lucidrains** [comment]
@zqevans btw, how are the new audio results looking?

**Comment by giorgioskij** [comment]
> @zqevans yea, i think that would overly complicate the repo for little gain
> 
> why not just anneal out the biases over an extra epoch of training?

I am facing the same problem. Do you have any suggestion on how to do that? The only way I'm thinking of is to add a strong L1/L2 regularization term to the biases and train until they converge to ~0. Do you have any ideas for a better way to do that?
