### ISSUE TITLE
Adding memmask to ContinuousTransformerWrapper

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/x-transformers#227]
@lucidrains could you add `memmask` to ContinuousTransformerWrapper please?
Thanks

**Comment by pfeatherstone** [comment]
Correct me if i'm wrong but the only difference between `ContinuousTransformerWrapper` and `TransformerWrapper` is one uses a `nn.Linear` layer to project inputs while the other using an `nn.Embedding` layer at the input. Those should be the only differences right?

**Comment by lucidrains** [comment]
@pfeatherstone oops, yea i added it

hmm, maybe at a later date, for now let us keep it separate
