### ISSUE TITLE
No return_embeddings in ViTransformerWrapper

### ISSUE THREAD

**Issue by neon5d** [lucidrains/x-transformers#23]
For image -> caption example in README

encoder = ViTransformerWrapper(
    image_size = 256,
    patch_size = 32,
    attn_layers = Encoder(
        dim = 512,
        depth = 6,
        heads = 8
    )
)

decoder = TransformerWrapper(
    num_tokens = 20000,
    max_seq_len = 1024,
    attn_layers = Decoder(
        dim = 512,
        depth = 6,
        heads = 8,
        cross_attend = True
    )
)

img = torch.randn(1, 3, 256, 256)
caption = torch.randint(0, 20000, (1, 1024))

encoded = encoder(img, **return_embeddings = True**)
decoder(caption, context = encoded) # (1, 1024, 20000)

There is no field "return_embeddings"

**Comment by lucidrains** [comment]
@neon5d added in https://github.com/lucidrains/x-transformers/releases/tag/0.9.1 !

**Comment by neon5d** [comment]
Thank you.
