### ISSUE TITLE
Scaling in normalization modules

### ISSUE THREAD

**Issue by davda54** [lucidrains/x-transformers#24]
Hi, thank you very much for publishing this awesome repository :) After studying the recent changes, I was confused with the introduction of `self.scale = dim ** -0.5` into `ScaleNorm` and `RMSNorm` in [this commit](https://github.com/lucidrains/x-transformers/commit/68ce7e7ccb169ad803ed7517b9b41352176eca85).

If I understand the code correctly, the modules multiply the normalized variable by `dim ** 0.5` ([these two lines](https://github.com/lucidrains/x-transformers/blob/9404f86f4923321a430b7cf969dd9065b054d7e2/x_transformers/x_transformers.py#L176-L177) divide the variable by `dim ** -0.5`). Since both the queries and the keys are multiplied like this, [the attention matrix](https://github.com/lucidrains/x-transformers/blob/9404f86f4923321a430b7cf969dd9065b054d7e2/x_transformers/x_transformers.py#L338) is effectively multiplied by `dim`, which goes against the usual practice to multiply it by `dim ** -0.5` (as you also do in the code).

I believe the normalized variables shouldn't be multiplied like this, what is the reason behind scaling it? Thank you very much for your time.

**Comment by lucidrains** [comment]
@davda54 I am just following the example put forth in the official repositories https://github.com/bzhangGo/rmsnorm/blob/master/rmsnorm_torch.py#L47 (RMS) https://github.com/tnq177/transformers_without_tears/blob/6b2726cd9e6e642d976ae73b9f696d9d7ff4b395/layers.py#L157 (Scale)

**Comment by davda54** [comment]
I see, turns out it was really just my confusion :) You divide it correctly by ![equation](https://latex.codecogs.com/png.latex?\sqrt{\frac{1}{\mathrm{dim}}\sum_{i=1}^{\mathrm{dim}}x_i^2}), as in the [RMSNorm paper](https://openreview.net/pdf?id=SygkZ3MTJE). Thanks for pointing me in the right direction, I'm closing this issue.
