### ISSUE TITLE
How to use "src_key_padding_mask" 

### ISSUE THREAD

**Issue by LutherLin** [lucidrains/x-transformers#253]
In PyTorch's official `nn.TransformerEncoder`, there is a parameter called `src_key_padding_mask`, which represents the mask for source data keys in each batch (optional). Does the `x_transformers` library offer a similar optional masking method, specifically designed to mask only the keys?
```python
        self.seqTransEncoder = ContinuousTransformerWrapper(
            dim_in = self.latent_dim, dim_out = self.latent_dim,
            emb_dropout = self.dropout,
            max_seq_len = 1024,
            attn_layers = Encoder(
                dim = self.latent_dim,
                depth = num_layers,
                heads = num_heads,
                ff_mult = int(np.round(ff_size / self.latent_dim)), 
                layer_dropout = self.dropout, cross_attn_tokens_dropout = 0,
            )
        )
```
I have defined the network structure above，then I want to use as：
```python
padding_mask = ...#torch.Size([32, 50]) 
xseq = ... #torch.Size([50, 32, 384])
output = self.seqTransEncoder(xseq, .........=padding_mask)[1:] 
```
Which mask should I use?

**Comment by lucidrains** [comment]
@LutherLin yup of course

in this repository, it is simply `mask` for the key padding mask, the shape accepted is `(batch, seq)`, and `True` denotes attend, `False` not attend

**Comment by lucidrains** [comment]
in your example

```python
padding_mask = ...#torch.Size([50, 32])   (batch, seq)
xseq = ... #torch.Size([50, 32, 384]) (batch, seq, feature dimension)
```

**Comment by BingliangLi** [comment]
> @LutherLin yup of course
> 
> in this repository, it is simply `mask` for the key padding mask, the shape accepted is `(batch, seq)`, and `True` denotes attend, `False` not attend

I think maybe this should goes into the readme? because for pytorch `nn.MultiheadAttention `states that `False` is attend and `True` is not: https://arc.net/l/quote/nhyzfosw
