### ISSUE TITLE
Is this the same "X-transformer" that being used in "X-Transformer: A Machine Translation Model Enhanced by the Self-Attention Mechanism" paper?

### ISSUE THREAD

**Issue by argadewanata** [lucidrains/x-transformers#257]
I read a paper titled "X-Transformer: A Machine Translation Model Enhanced by the Self-Attention Mechanism" on https://www.mdpi.com/2076-3417/12/9/4502.

Is this the same "X-Transformer"?

**Comment by lucidrains** [comment]
@argadewanata hey Rere! this repository actually predates that paper, so just a name collision
