### ISSUE TITLE
[Feature Request] CoPE from Meta

### ISSUE THREAD

**Issue by JLenzy** [lucidrains/x-transformers#268]
https://arxiv.org/abs/2405.18719

This paper proposes a new positional encoding technique, wherein they compute and add 'gate values'. This is demonstrated to solve a number of SoTA LLM issues, such as word counting. 

The paper even shows a straightforward PyTorch implementaiton in the addendum. Any chance this could be added? I would love to benchmark it, particularly against other relative positional methods.

**Comment by lucidrains** [comment]
agreed and it is already in there https://github.com/lucidrains/x-transformers/blob/main/tests/test_x_transformers.py#L73

**Comment by JLenzy** [comment]
Okay, you are amazing! Thank you. 
Since I don't see it on the docs, do you (or your friends) have any experience yet from training yet? I'll probably run some tests on it later this week, but curious to hear if there is any intuition yet about the performance it gives

**Comment by lucidrains** [comment]
@JLenzy my take is that this is evidence for moving to sub-quartic https://github.com/lucidrains/quartic-transformer

there is no one i know who is exploring this, so appreciate it if you get back to me if you see something!
