### ISSUE TITLE
encoder.to_logits.weight doesn't update

### ISSUE THREAD

**Issue by guillaumeguy** [lucidrains/x-transformers#273]
It seems that parameter `encoder.to_logits.weight` in an Encoder/Decoder is not part of the forward pass. This creates problems when running DDP. 

Should these weights be removed in such case?

Reproducible example:
- https://gist.github.com/guillaumeguy/ff96c1f337d99109a6ab2666a896ad3c

**Comment by lucidrains** [comment]
@guillaumeguy ah yes, that shouldn't be there

could you try 1.35.2?

**Comment by guillaumeguy** [comment]
Works great! Thank you for the quick turnaround!

**Comment by lucidrains** [comment]
@guillaumeguy you are one of the few using a full encoder decoder transformer

how are you using it?
