### ISSUE TITLE
Adding a latent vector at each layer

### ISSUE THREAD

**Issue by JLenzy** [lucidrains/x-transformers#274]
There's a handful of Transformer-VAE papers that add a form of residual network, wherein the latent vector _z_ is summed with the hidden state _h_ prior to the attention mechanism at each layer of the decoder:

https://arxiv.org/pdf/1807.04863
https://arxiv.org/abs/2105.04090 (look up 'in-attention conditioning')

I was wondering if there is potentially already a functionality within x-transformers that could be used to achieve this same result?

**Comment by lucidrains** [comment]
@JLenzy hey, there isn't, the only thing i've added recently is unet-like skip connections, as some people have reported good results in DiT setting

have you seen remarkable results?

**Comment by lucidrains** [comment]
the other reason i added the unet skip connections is because it corroborated [a paper](https://arxiv.org/abs/2107.10342) (they only do first to just before the last) whose author i trust

**Comment by lucidrains** [comment]
@JLenzy if you can provide some plots and graphs, happy to try it out myself before adding it

**Comment by lucidrains** [comment]
ah, i recognize the authors from the last paper

will pass on this

**Comment by JLenzy** [comment]
Hey there, no worries. In the context of my work (music generation) the technique can be a game-changer, but I understand if that's a bit niche for support. Appreciate all your amazing work with xtransformers!

**Comment by lucidrains** [comment]
@JLenzy oh, so it works well? 🤔 like for preventing posterior collapse in VAE? has anyone written a paper about this for the more popular VQGAN "VAE"?

**Comment by lucidrains** [comment]
i thought most of music generation research moved on towards using autoregressive transformers or diffusion (stable audio)?

**Comment by lucidrains** [comment]
@JLenzy you should try the recently added [unet skip connection setting](https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L1329), would be curious if it served the same purpose
