### ISSUE TITLE
return_only_embed

### ISSUE THREAD

**Issue by JLenzy** [lucidrains/x-transformers#277]
I'd like to double check if my understanding is correct here:

```
model = TransformerWrapper(
        num_tokens=20000,
        max_seq_len=2048,
        return_only_embed=True,
        attn_layers=Decoder(
            dim=512,
            depth=12,
            heads=16,
```

If I instantiate this with the `return_only_embed=True` and run a standard forward pass with no additional args (besides src / mask) will this return the pure hidden state from the final attention layer?

**Comment by lucidrains** [comment]
@JLenzy hey Julian! yes, but after a final norm that has become a standard in pre-norm transformers

**Comment by JLenzy** [comment]
Thank you sir! That's a really interest paper, I'll have to check dig deeper into it. As you said, looks to be approaching a different issue but with a similar solution.

**Comment by lucidrains** [comment]
@JLenzy ok, yea i think i'll just add it later today. make sure to turn over this rock

**Comment by lucidrains** [comment]
@JLenzy want to try [this flag](https://github.com/lucidrains/x-transformers/commit/0d4b985bf2fb4c73b46df7bb0e6ea405920c0572#diff-10b0fcd6b3df77bf858789e5e9fb0b0662139dc0b1d66430223123062a503f8cR312) in your vae decoder?

**Comment by lucidrains** [comment]
think this issue can be closed

**Comment by JLenzy** [comment]
Hi @lucidrains , thank you for your continued work on this! But unfortunately it's a bit different than the 'in-attention' mechanism. It is more of a replacement for cross attention than a residual network. In the original paper, they pass in the input (x) as well as a separate, latent vector (z) to the decoder. The latent vector has the dim of [b, c] and is repeated across [t] timesteps of the corresponding x vector. This is what is summed with x prior to each attention layer. So it's a residual latent vector. I believe (please correct if wrong) that your implementation above is a projection + summation of the original x input. 

Btw I'd be happy to take a crack at this with a PR if you are open for it! I've got a few working versions with my own custom attention implementations. 

```
z = z.unsqueeze(1).expand(-1, tgt_seq_len, -1)
output = src
if self.norm and self.pre_layer_norm:
      output = self.norm(output)
for i in range(self.n_layers):
     # In-Attention Conditioning for decoders
     if self.in_attention and z is not None:
           output = output + z
     output = self.layers[i](
              output,
              src_mask=mask,
              src_key_padding_mask=src_key_padding_mask
      )

**Comment by lucidrains** [comment]
@JLenzy ohh i see, would it help if `AttentionLayers` simply allowed for accepting `in_attn_conditioning_z: Float['b c']` and did the rest?

more importantly, have you replicated the results?

**Comment by lucidrains** [comment]
@JLenzy thank you for sharing that! apologize for waving it off so quickly before

you should be able to pass it in as [`in_attn_cond`](https://github.com/lucidrains/x-transformers/commit/391df8e919e72e7ef603d4a69f5941b421e3b75c#diff-2e64ac8840195d7dc3e07a3aac70b50bbab1cdf80f3a7432be40105e6097fc0aR1676) now

**Comment by JLenzy** [comment]
Not a worry at all, really appreciate all your work here! I'll be sure to let you know how it goes on our end.
