### ISSUE TITLE
forgetting transformers

### ISSUE THREAD

**Issue by faresobeid** [lucidrains/x-transformers#281]
Maybe can try https://openreview.net/forum?id=q2Lnyegkr8.
Also for the value residual implementation I see u dont average the values, not sure if thats on purpose, and form the paper it seems like resformer + neutreno is best but im unsure how that looks exactly

**Comment by lucidrains** [comment]
@faresobeid yes, i was just reading "forgetting transformer" yesterday but haven't fully digested it yet

oh, was value residual averaged? and yea i noticed they had a combo that worked better, but i'd need another hyperparameter for that (to specify resformer only, neutreno only, both)

**Comment by faresobeid** [comment]
Ya the forgetting transformer is basically mamba 2 style decay but on the attn mask, seems cool. For resformer + neutreno is that just doing both in ur code like that would u say?

**Comment by lucidrains** [comment]
@faresobeid yea, except it should be more powerful than associative scan based rnn, as you get a separate row per token

ohh, i see what you mean. they won't be averaged, as the two papers apply the residual in different places

**Comment by lucidrains** [comment]
@faresobeid but yip, i'm open to adding it once i see a positive experiment. think i will for this paper

**Comment by faresobeid** [comment]
> @faresobeid yea, except it should be more powerful than associative scan based rnn, as you get a separate row per token
Hm not sure wym as mamba 2 decay is data dependent

**Comment by faresobeid** [comment]
> @faresobeid but yip, i'm open to adding it once i see a positive experiment. think i will for this paper

Ya i mean tbf it is basically data dependent alibi so must be better than alibi at least

**Comment by lucidrains** [comment]
im pretty sure eventually we'll just end up with [this](https://github.com/lucidrains/quartic-transformer) in a year or two

**Comment by lucidrains** [comment]
> > @faresobeid yea, except it should be more powerful than associative scan based rnn, as you get a separate row per token
> 
> Hm not sure wym as mamba 2 decay is data dependent

in transformers, each token will aggregate other tokens with their own separate forgetting pattern

that isn't the case with associative scan rnn

**Comment by faresobeid** [comment]
Well technically in the attn view they do the same thing here. You can imagine at inference ur row will all be multiplied by F then append the new token. Rnns do the same but issue is they add these values rather than concatenate (trade off), but forgetting should work the same (obv the forgetting here will learn different patterns bcs theres no compression so would forget more compared to if used in an rnn)

**Comment by faresobeid** [comment]
On another note u could also implement this optimizer, tbh i really like it https://openreview.net/forum?id=L9eBxTCpQG

**Comment by lucidrains** [comment]
> Well technically in the attn view they do the same thing here. You can imagine at inference ur row will all be multiplied by F then append the new token. Rnns do the same but issue is they add these values rather than concatenate (trade off), but forgetting should work the same (obv the forgetting here will learn different patterns bcs theres no compression so would forget more compared to if used in an rnn)

think we may be referring to two different things

agreed the forgetting comes out the same. the difference is each attention row allows a query token to aggregate the past differently

**Comment by lucidrains** [comment]
> On another note u could also implement this optimizer, tbh i really like it https://openreview.net/forum?id=L9eBxTCpQG

ah, feel free to pitch this to me over Signal

I usually don't implement too many optimizer papers

**Comment by lucidrains** [comment]
@faresobeid oh that optimizer paper already has code submitted (supplementary zip)

**Comment by faresobeid** [comment]
> > On another note u could also implement this optimizer, tbh i really like it https://openreview.net/forum?id=L9eBxTCpQG
> 
> ah, feel free to pitch this to me over Signal
> 
> I usually don't implement too many optimizer papers

Signal?

**Comment by faresobeid** [comment]
> @faresobeid oh that optimizer paper already has code submitted (supplementary zip)

Oh didnt realise lol

**Comment by lucidrains** [comment]
actually reread the paper last night and realized they aren't doing it the way i thought they would

i'll offer my version of it (as well as another one using complex numbers) once i replicate the findings in this paper. you are right this is simply a learned data-dependent alibi

**Comment by faresobeid** [comment]
Hm tbh they did it exactly how I would've thought so im curious abt how u think it should be done. Also they do mention this connection which seems key and a big improvement over alibi
<img width="1009" alt="Screenshot 2024-10-28 at 14 02 52" src="https://github.com/user-attachments/assets/0b2991f7-d93c-4e15-9682-8d56accb3750">

**Comment by lucidrains** [comment]
@faresobeid i think they are sharing the same forgetting gates across all rows by projecting off the input sequence, but i was thinking of having separate query and key heads (< `dim_head`), so each row can decide independently

**Comment by lucidrains** [comment]
@faresobeid i'll get to it by mid next month

**Comment by lucidrains** [comment]
@faresobeid probably clearer once i code it up

feel free to reach out over Signal if you want to discuss further

**Comment by faresobeid** [comment]
Whats ur username?

**Comment by lucidrains** [comment]
https://lucidrains.github.io/

**Comment by lucidrains** [comment]
hmm, doing the first run this morning and does not look that good early on

**Comment by lucidrains** [comment]
![W B Chart 10_29_2024, 9_12_34 AM](https://github.com/user-attachments/assets/860c77b1-bb00-43f9-959e-8b500699de38)

oh nope, just me sucking at running experiments

i'm seeing it, checking it in

**Comment by faresobeid** [comment]
Nice lmk when the code is up so i can take a look to see if there is anything wrong. Also they mention how qk norm is important so better to use it if u arent

**Comment by lucidrains** [comment]
@faresobeid code is surprisingly short, let me rerun a few things before checking it in

**Comment by lucidrains** [comment]
@faresobeid ok, here you go https://github.com/lucidrains/x-transformers/commit/222f36052b667654cc1061eb7b6ba2b9ba492415#diff-2e64ac8840195d7dc3e07a3aac70b50bbab1cdf80f3a7432be40105e6097fc0aR502 let's leave the issue open so you can let me know how it fares on your setup

i'll probably throw in that idea for row independent forget gates tomorrow before closing this

**Comment by lucidrains** [comment]
@faresobeid that transpose trick is cool! thanks, got some of those changes into 1.41.1, will circle back to this tomorrow morning

**Comment by faresobeid** [comment]
Ya although should point out its technically less numerically accurate (not sure by how much) so depends on how much of a speed up u get

**Comment by lucidrains** [comment]
@faresobeid depending on how successful this technique ends up becoming in the coming months, may need to integrate into flash attention kernel, through triton or otherwise

**Comment by faresobeid** [comment]
Oh nice ur per row idea makes sense now, u could also try a low rank projection rather than a small head size (Rnns typically use a low rank projection for the decay to save params), also defo try dividing by 16 or 8 after the log, main job is to push decay values to be close to 1 at initialisation which is shown here https://arxiv.org/abs/2410.11135 and here https://openreview.net/forum?id=DHVjLvSps6 to be vital (of course this is for rnns but makes sense for transformers as at initialisation u want it to not forget stuff too much)

**Comment by lucidrains** [comment]
@faresobeid hey yes, you noticed

sounds good, i've made your proposed factor a hyperparameter, and yes i'm familiar with Trockman's "mimetic init"

**Comment by lucidrains** [comment]
@faresobeid think i can close this issue early; it didn't take 2 weeks after all! these things are hard to predict with papers

**Comment by lucidrains** [comment]
@faresobeid also, i added https://github.com/lucidrains/x-transformers/commit/be4734757317bc2a1b9c808dc00b20a5c87a454f#diff-2e64ac8840195d7dc3e07a3aac70b50bbab1cdf80f3a7432be40105e6097fc0aR522 in the case you want to play with it

this could allow the network to pay attention to parts of the past without having to attend locally

**Comment by faresobeid** [comment]
To sort of reopen this, see https://github.com/Zcchill/Value-Residual-Learning/issues/1#issuecomment-2449050800 where first the code for neutrino plus resformer is there (didn't check if it's the same as urs), but also in the first pdf linked they show lambda = 1 (v + v_1) is quite worse than dividing by 2 after so u might want to add that

**Comment by lucidrains** [comment]
@faresobeid thank you Fares, running the experiment now and indeed i made a mistake and it is a big improvement
