### ISSUE TITLE
qk_norm and kv_heads conflict

### ISSUE THREAD

**Issue by alexdemartos** [lucidrains/x-transformers#282]
Hi @lucidrains , hope all is good.

I believe there is a conflict when using both qk_norm and kv_heads != heads that should be solved changing:

https://github.com/lucidrains/x-transformers/blob/eeed50391855f8d552edc866701952f38015e415/x_transformers/x_transformers.py#L1022

to:
`self.qk_norm_k_scale = nn.Parameter(torch.ones(kv_heads, 1, dim_head))`

Thanks!

**Comment by lucidrains** [comment]
thanks Alejandro!

**Comment by alexdemartos** [comment]
> @alexdemartos have you seen [e2-tts](https://github.com/lucidrains/e2-tts-pytorch) btw?

Yes, this was an interesting work. I tried a very similar approach. In my case it works generally OK, but I'm finding some stability issues with long sequences (basically the model doesn't seem to extrapolate well to longer sequences than those seen during training). Explicit duration prediction is robust to long sequences at the expense of minor naturalness degradation.

What was your experience?

**Comment by lucidrains** [comment]
@alexdemartos indeed, although i've also heard it improves with training on said longer sequences

a student has open sourced quite a [good model](https://github.com/SWivid/F5-TTS) based on e2-tts. think we will see a lot of follow up research along these lines soon

**Comment by alexdemartos** [comment]
> I'm very much interested in works trying to address stability/hallucination issues in both AR and E2TTS-like architectures

FYI, on this topic I just found about a new Tacotron-series paper (Very Attentive Tacotron):
https://arxiv.org/pdf/2410.22179

**Comment by lucidrains** [comment]
@alexdemartos nice! so some position engineering and an RNN does the trick

**Comment by lucidrains** [comment]
@alexdemartos have you ever tried adding relative positions to the cross attention block? i have a few ideas

**Comment by alexdemartos** [comment]
> @alexdemartos have you ever tried adding relative positions to the cross attention block? i have a few ideas

Only for synchronous sequences, so not really. I guess the tricky part here is how to solve the alignment problem between target and cross-attended sequences (i.e. how to center the relative position in the cross-attention sequence at each target timestep). Happy to hear about your ideas!

**Comment by lucidrains** [comment]
@alexdemartos haha don't get too excited, its just a simple idea for generating attention bias with monotonicity

**Comment by lucidrains** [comment]
@alexdemartos i'll throw it into a separate branch and ping you when i do

**Comment by lucidrains** [comment]
@alexdemartos position engineering is the new feature engineering
