### ISSUE TITLE
Tokenformer

### ISSUE THREAD

**Issue by iiLaurens** [lucidrains/x-transformers#286]
[TokenFormer](https://arxiv.org/abs/2410.23168) looks quite promising as it seems to tokenize the parameters of the model itself, adding a new degree of flexibility that allows the input to compose the most fitting model weights. It is like MoE on steroids. 

To me it seems that a TokenFormer is a generalization of traditional transformers. The FFN layer of the latter can be seen as a single-parameter-token TokenFormer, similarly to how a traditional transformer can be viewed as a single-expert MoE.

As such I think it could be implemented on top of x-transformers to achieve better scaling by taking any existing model and topping it up with more parameters. What do you think?

**Comment by lucidrains** [comment]
ah yes, while i don't think it is [very novel](https://arxiv.org/abs/2012.14913) the scaling experiments are still kinda cool

don't they already have their code open sourced?

**Comment by lucidrains** [comment]
think i'll wait for a bit to see if this practice picks up without any clear deficiencies. it will be too big of a change to integrate into x-transformers at this point in time

**Comment by lucidrains** [comment]
@iiLaurens read the paper in more detail

not a believer, will pass on this
