### ISSUE TITLE
[new paper] TokenFormer 

### ISSUE THREAD

**Issue by guillaumeguy** [lucidrains/x-transformers#287]
This novel paper could be a nice addition to the features of the repo:

https://arxiv.org/abs/2410.23168

the authors replaced the projections with another attention and claimed great gains in training speed

**Comment by lucidrains** [comment]
@guillaumeguy hey Guilllaume, this was brought up already

unfortunately, not a believer yet

**Comment by guillaumeguy** [comment]
Always keep to have a certain degree of skepticism! Thanks for looking into it.
