### ISSUE TITLE
Why is 32 the minimum possible value for rotary_emb_dim?

### ISSUE THREAD

**Issue by slabodkin** [lucidrains/x-transformers#296]
https://github.com/lucidrains/x-transformers/blob/5791a851c07909ae14d18b96392ef4a2c4db6d8e/x_transformers/x_transformers.py#L1583

Is there a reason behind using `max` here? It breaks the code if attention head dim is smaller than the default (64):
```python
import torch
from x_transformers import TransformerWrapper, Encoder

model = TransformerWrapper(
    num_tokens = 21,
    max_seq_len = 40,
    attn_layers = Encoder(
        dim = 10,
        depth = 4,
        heads = 3,
        attn_dim_head = 4,
        rotary_pos_emb = True,
    ),
)
x = torch.randint(0, 21, (1, 40))
model(x)
```

  File "<..>/x_transformers/x_transformers.py", line 688, in apply_rotary_pos_emb
    t = (t * freqs.cos() * scale) + (rotate_half(t) * freqs.sin() * scale)
         ~~^~~~~~~~~~~~~
RuntimeError: The size of tensor a (4) must match the size of tensor b (32) at non-singleton dimension 3

**Comment by lucidrains** [comment]
@slabodkin hey Andrei

that's just the empirical value the open source community has found below which rotary embeddings starts to suffer

realistically, your attention head dimension should never fall below 32, 16 minimum

**Comment by slabodkin** [comment]
Hi, thanks for answering so quickly! 

> realistically, your attention head dimension should never fall below 32, 16 minimum

This may be not be true in some settings and types of data (e.g. short-ish protein sequences, where both the sequence length and the alphabet size are low).
But if the ropes start to suffer, then I guess one shouldn't use them in such settings :) 

Maybe throwing an exception in the `RotaryEmbedding` constructor would be a good idea? Or at least a warning of some sort

**Comment by lucidrains** [comment]
@slabodkin oh that is true, did not consider non-language settings, let me transform that into a warning

**Comment by lucidrains** [comment]
@slabodkin want to try the latest version?

**Comment by lucidrains** [comment]
@slabodkin hehe cute cat
