### ISSUE TITLE
[Bug] Custom alibi position fails for flash attention

### ISSUE THREAD

**Issue by Aceticia** [lucidrains/x-transformers#298]
Hi! I've been revisiting the custom position alibi again, and I found that setting `attn_flash=True` will fail. It looks like the following line forgot to account for the attention bias being 4D when custom positions are passed in. Should be an easy fix?
https://github.com/lucidrains/x-transformers/blob/57efd7770f2f5df0ff7b4ffcbd623750b584e850/x_transformers/attend.py#L373

**Comment by lucidrains** [comment]
haha yes indeed, my bad 

I'm off for the holidays and will be back mid next week

If you want to attempt a PR for this, by all means!
