### ISSUE TITLE
[Feature request] Rotary positional embedding with custom positions

### ISSUE THREAD

**Issue by Aceticia** [lucidrains/x-transformers#299]
Hello again! I've found rotary positional embeddings to be *a lot* better compared to alibi in our experiments, so I'd like to try to replicate the experiment of custom position alibi with rotary positional embedding and see what happens. As usual, this doesn't look too hard and let me know if you would like me to submit a pull request for this. If I understand it correctly, the following are all we need to change:

1. When [creating the frequencies from positions](https://github.com/lucidrains/x-transformers/blob/57efd7770f2f5df0ff7b4ffcbd623750b584e850/x_transformers/x_transformers.py#L658), include a `b` for batch if the input is custom position, and expand b=1 if the input is not custom position (same for all samples).
2. When [taking only the relevant chunk of frequency](https://github.com/lucidrains/x-transformers/blob/57efd7770f2f5df0ff7b4ffcbd623750b584e850/x_transformers/x_transformers.py#L682), add colon to handle the extra `b` dimension now.

Thanks to your generous use of ellipses, the rest of the code handles itself neatly.

**Comment by lucidrains** [comment]
yea I believe you, that's been my experience as well

will take a look post holiday
