### ISSUE TITLE
Rotary Embedding for different q, k sequence length

### ISSUE THREAD

**Issue by frankang** [lucidrains/x-transformers#38]
In the attention layer, only the rotary embedding for the x input (query) is calculated, which would leads to error when key's sequence length does not equal the seqlen of the input x.
https://github.com/lucidrains/x-transformers/blob/4b395abae6792a5166c43f186ff3fdd548c59820/x_transformers/x_transformers.py#L566
`        rotary_pos_emb = self.rotary_pos_emb(x)`

**Comment by lucidrains** [comment]
@frankang ohh, could you send me a reproducible script? are you adding memory key / values or is this cross attention setting? (I think in cross attention rotary should be disabled?)

**Comment by frankang** [comment]
Not yet, it occurs when we want to to do an encoder-decoder attention, where the sequence of the decoder q is not the same as the sequence of encoder context (k)
According to `q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> b h n d', h = h), (q, k, v))`, 
suppose a _q_ from the decoder is of the dimension (2, 8, 20, 64), and _k_ from the encoder is (2, 8, 30, 64),
the generated _rotary_pos_emb_ dim is (1,1, 20, 64), so applying the rotary embedding _rotary_pos_emb_ on _k_ results in error because the third dimension doesn't match.

**Comment by vvvm23** [comment]
Hi, I have a similar scenario where I want to use rotary embeddings in a cross-attention scenario, but found it gets disabled when `context` exists.

Couldn't we simply generate two sets of rotary embeddings? Applying the first to the Q and the second to K? Is there some reason I am missing that would mean this isn't possible?

**Comment by zaptrem** [comment]
> Hi, I have a similar scenario where I want to use rotary embeddings in a cross-attention scenario, but found it gets disabled when `context` exists.
> 
> Couldn't we simply generate two sets of rotary embeddings? Applying the first to the Q and the second to K? Is there some reason I am missing that would mean this isn't possible?

@lucidrains 

Following up on this as I'm running into the same question while chasing down a torch dynamo bug. Would the solution mentioned above work? If not, what's the preferred way to make sure the cross-attention layers have some sort of positional info (e.g., for a text to image model)?

**Comment by lucidrains** [comment]
@zaptrem how does relative positions make sense in your scenario? what kind of positions would a single token of text have to an image token?

**Comment by lucidrains** [comment]
the only place where relative positions would make sense is when you are doing [cross resolution attention](https://github.com/lucidrains/vit-pytorch?tab=readme-ov-file#cross-vit) of the same input. but that's a special case that i don't think it warrants the extra complexity in this repository for

**Comment by zaptrem** [comment]
> @zaptrem how does relative positions make sense in your scenario? what kind of relative positions would a single token of text have to an image token?

I was thinking more position within the sentence itself (e.g., "A sign that says 'We Like Ike'" needs the sign to say that instead of 'Ike We Like'). Maybe I'm misunderstanding something about how it works?

**Comment by lucidrains** [comment]
@zaptrem what you are thinking is absolute positions, not relative

**Comment by zaptrem** [comment]
> @zaptrem what you are thinking is absolute positions, not relative

Don't modern transformers like Llama use only relative position encodings to understand things like sentence order? Why would only absolute work in this case? Also, it seems like absolute position encodings (even when enabled in xtransformers) aren't applied to context?

**Comment by lucidrains** [comment]
@zaptrem llama only uses relative, because there's research that shows with a causal mask, the transformer emergently figures out absolute, so it is redundant. however, this is unclear for encoders, so you can just stick another absolute position embedding on top of rotary

**Comment by lucidrains** [comment]
@zaptrem i automatically disable absolute positions when rotary embeddings are present, but if somehow you are using an encoder and wish to have both (so that cross attention can utilize it) try the following

```python
model = TransformerWrapper(
    num_tokens = 20000,
    max_seq_len = 512,
    attn_layers = Decoder(
        dim = 512,
        depth = 6,
        heads = 8,
        rotary_pos_emb = True,
        disable_abs_pos_emb = False # set this to False
    )
)
```

**Comment by zaptrem** [comment]
> @zaptrem i automatically disable absolute positions when rotary embeddings are present, but if somehow you are using an encoder and wish to have both (so that cross attention can utilize it) try the following in the latest version
> 
> ```python
> model = TransformerWrapper(
>     num_tokens = 20000,
>     max_seq_len = 512,
>     attn_layers = Decoder(
>         dim = 512,
>         depth = 6,
>         heads = 8,
>         rotary_pos_emb = True,
>         disable_abs_pos_emb = False # set this to False
>     )
> )
> ```

Thanks! but wouldn't this only apply the abs_pos_emb to x and not the context (which it is my understanding we need to know the sign order)? Also, before moving to this repo I was using my own transformer that only had RoPE (no absolute) and it seemed to be working okay in small test sequences.

**Comment by lucidrains** [comment]
you can just add your own absolute positions to your context. if your context is coming from another decoder, then it should be present already

**Comment by zaptrem** [comment]
> you can just add your own absolute positions to your context, if it is coming from an encoder that only has relative positions (quite rare). if your context is coming from another decoder, then it should be present already

Makes sense. Half is coming from T5, they use a non-RoPE non-alibi relative embedding so I'd need my own for that right? The other half is tokens passed through a single embedding layer so definitely I'll add my own there.
