### ISSUE TITLE
Talking head postprocess seems to be wrong

### ISSUE THREAD

**Issue by usamec** [lucidrains/x-transformers#4]
Output of this line is not used anywhere: https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L264

**Comment by lucidrains** [comment]
yikes! how embarrassing lollll

**Comment by lucidrains** [comment]
fixing now

**Comment by lucidrains** [comment]
@usamec fixed! thank you for catching this https://github.com/lucidrains/x-transformers/releases/tag/0.2.5
