### ISSUE TITLE
Reason for doing partial rotary embedding?

### ISSUE THREAD

**Issue by frankang** [lucidrains/x-transformers#40]
In a recent commit only half the head vector is "rotated", could this improve the overall performance? Thanks!
https://github.com/lucidrains/x-transformers/commit/4b395abae6792a5166c43f186ff3fdd548c59820
```
-    self.rotary_pos_emb = RotaryEmbedding(dim_head) if rotary_pos_emb else always(None)
+    rotary_emb_dim = max(default(rotary_emb_dim, dim_head // 2), 32)
```

**Comment by lucidrains** [comment]
@frankang rotary is a fairly new finding, so by no means is all the exploration done - let us know what you find!

**Comment by frankang** [comment]
Thanks! will follow up if I get some new results.
