### ISSUE TITLE
[Featue request] Expire span : Learning to Forget by Expiring

### ISSUE THREAD

**Issue by mistycube** [lucidrains/x-transformers#44]
This is a nice feature that can complement this project:
Video by Yannic Kilcher: https://www.youtube.com/watch?v=2PYLNHqxd5A

**Comment by lucidrains** [comment]
@mistycube Hi! I tried to build this some time ago https://github.com/lucidrains/learning-to-expire-pytorch but as I progressed, the more flaws I uncovered. I eventually gave up on it

**Comment by linzino7** [comment]
> @mistycube Hi! I tried to build this some time ago https://github.com/lucidrains/learning-to-expire-pytorch but as I dug deeper into the code, the more flaws I uncovered with the approach. I eventually gave up on it

Hi @lucidrains ,
 Could you please tell me what flaws you discover?
