### ISSUE TITLE
Feature request for another relative positional embedding

### ISSUE THREAD

**Issue by hadaev8** [lucidrains/x-transformers#6]
This paper claim to have the best relative positional embedding to the moment
https://arxiv.org/abs/2009.13658

Here is an example of implementation
https://github.com/hadaev8/transformers/blob/37712fdd1cb9ed83ebcc888f184296c135f90be4/src/transformers/models/bert/modeling_bert.py#L271

The only thing that should be considered for this lib is the distance of memory tokens.

**Comment by lucidrains** [comment]
Cool! Would it be similar to https://github.com/lucidrains/x-transformers#position-infused-attention except that instead of sinusoidal, it is learned? (And subtract the <Aij . Aij> bias term

**Comment by lucidrains** [comment]
Oh my mistake, it is different

**Comment by lucidrains** [comment]
So this is like Shaw's, but also added to the key side and subtracting out the bias term

**Comment by lucidrains** [comment]
This is really interesting! Have you tested this at all? Perhaps for memory tokens to and from attention can get its own special vector (reserve an integer for it in the distance matrix)

**Comment by lucidrains** [comment]
It would be similar to how it is untied here https://arxiv.org/abs/2006.15595

**Comment by hadaev8** [comment]
Yes, I had in mind what paper too.
Guess cls token should be excluded from the distance and have its own embedding (like image patch in VIT for example).
Actually, it would be nice to exclude some tokens from distance embedding.
I wanna try style tokens (for conditional gan) in the future.

I tuned huggings face bert with this distance and it works fine. Default bert failed with long samples on inference, but now it seems to be fine (honestly, my encoder-decoder tts still fail to produce samples longer than seen in the train dataset).
Now I wanna use your cool features to make what bert a bit better.
Guess, it would be easy to transfer weights from huggings face model.

**Comment by lucidrains** [comment]
@hadaev8 ok, feel free to leave this issue open, I'll have to run an experiment to see how much of a gain it is

**Comment by lucidrains** [comment]
@hadaev8 I consulted a researcher friend, and he wasn't too impressed by the GLUE results in Table 3, so I'm leaning towards not adding this

**Comment by hadaev8** [comment]
@lucidrains 
Well, tablet 3 not really important.
Because the model was evaluated on the same sample lengths as in train data.
Bert sure will be ok on in domain lengths.

The question is if this method generalizes long samples better than implemented here t5 relative positional embedding.
It's hard for me to test. 😢

**Comment by lucidrains** [comment]
@hadaev8 T5 relative pos should work just as well in generalizing to longer sequence lengths, i'm fairly confident (without data lol)

**Comment by hadaev8** [comment]
@lucidrains 
Finally done the experiment and found better relative embedding done its thing while t5 rel pos bias can't generalize for longer samples.
