### ISSUE TITLE
attn_dropout and ff_dropout implemented?

### ISSUE THREAD

**Issue by antorsae** [lucidrains/x-transformers#66]
They're mentioned it in the documentation, however they are not present in the source code.

**Comment by lucidrains** [comment]
@antorsae yup, they are! i have a system where keyword arguments for the Attention class is prepended with `attn_`, while for feedforwards they are `ff_`

**Comment by lucidrains** [comment]
https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py#L645

**Comment by antorsae** [comment]
Thanks a lot. My bad.
