### ISSUE TITLE
Cannot find the definition of `self.gate_v`

### ISSUE THREAD

**Issue by imflash217** [lucidrains/x-transformers#67]
Hi @lucidrains ,

I cannot find the definition of the variable `self.gate_v` as called in

https://github.com/lucidrains/x-transformers/blob/d5114991e84ea9a0332e636fca8b355f00523688/x_transformers/x_transformers.py#L598

There is another parameter by the name `self.gate_values` as seen in 
https://github.com/lucidrains/x-transformers/blob/d5114991e84ea9a0332e636fca8b355f00523688/x_transformers/x_transformers.py#L414

I suppose this is a typo....Or am I understanding something wrong?
Thanks

**Comment by lucidrains** [comment]
@imflash217 Hi Vinay! Thanks for catching this bug! It should be fixed in 0.20.5
