### ISSUE TITLE
Cannot find the usage of `mem` 

### ISSUE THREAD

**Issue by imflash217** [lucidrains/x-transformers#68]
Hi,
I cannot find the usage of `mem` as mentioned below
https://github.com/lucidrains/x-transformers/blob/188cbd783f1b1efa9fb79ef291f3aceaeab9c8e6/x_transformers/x_transformers.py#L984

I see another variable `mems` (below inside `zip(mems, hiddens)`) which represents the memory part which I understand. 
https://github.com/lucidrains/x-transformers/blob/188cbd783f1b1efa9fb79ef291f3aceaeab9c8e6/x_transformers/x_transformers.py#L990

Is `mem` incorrectly typed? 
Should `mem` instead be `mems`? 
Or am I understanding incorrectly?
Thanks

**Comment by lucidrains** [comment]
@imflash217 Hi Vinay - that memory is actually the memory from the Memory Transformers paper, and not the memory from the Transformer-xl paper (confusing I know)

so it is actually correct, although I should probably name it something else 🤔

**Comment by imflash217** [comment]
Makes sense now. Thanks. 😊

**Comment by stas-sl** [comment]
So it seems currently there is no way to access memory tokens output? I'd like to have a few additional classification heads besides just sequence tokens, so I was thinking that memory tokens could be used for that purpose. Or they are only intended to be used internally to allow `attend to nothing` but not to have additional outputs?

**Comment by lucidrains** [comment]
@stas-sl yea sure, try `return_intermediates = True` and accessing it as `.memory_tokens`?

**Comment by lucidrains** [comment]
@stas-sl are you doing research on the memory / register tokens?

**Comment by stas-sl** [comment]
Awesome, thanks! 

I wouldn't call it research ) Just playing around, basically what I wanted is to use them akin to CLS tokens as mentioned in the README
