### ISSUE TITLE
Rezero doesn't gate FFs

### ISSUE THREAD

**Issue by nostalgebraist** [lucidrains/x-transformers#69]
If I understand correctly, passing `use_rezero=True` currently does the following:

- for attn layers: removes the prenorm + gates the residual branch
- for FF layers: only removes the prenorm

This doesn't match the Rezero paper / [original code](https://github.com/majumderb/rezero/blob/master/rezero/transformer/rztx.py#L69-L82), which gates both attn and FF with a shared scalar.

### Details

`use_rezero` affects behavior only through its affects on `norm_fn` and `branch_fn`, set here:

https://github.com/lucidrains/x-transformers/blob/55ca5d96c8b850b064177091f7a1dcfe784b24ce/x_transformers/x_transformers.py#L694-L695

The `norm_fn` is used for both attn and FF, but the `branch_fn` is only used for attn:

https://github.com/lucidrains/x-transformers/blob/55ca5d96c8b850b064177091f7a1dcfe784b24ce/x_transformers/x_transformers.py#L759-L774

### Past behavior

If I understand correctly, the current behavior was introduced in [this commit adding residual attn](https://github.com/nostalgebraist/x-transformers/commit/257fee10394c3cfb3467537dba53d8a610dc8aee).

Before that commit, use_rezero would gate both attn and FF.

However, it gated the inputs (via prenorm_fn) rather than the outputs, and used separate scalars for the attn and FF:

https://github.com/lucidrains/x-transformers/blob/c090733bbeabcc4480bcf03fc19f0ef76e7129d4/x_transformers/x_transformers.py#L295

https://github.com/lucidrains/x-transformers/blob/c090733bbeabcc4480bcf03fc19f0ef76e7129d4/x_transformers/x_transformers.py#L320-L331

**Comment by pfeatherstone** [comment]
What was the reason for removing ReZero? Paper looks interesting
