### ISSUE TITLE
Understanding the key and value transmission from the encoder output to the decoder

### ISSUE THREAD

**Issue by CDitzel** [lucidrains/x-transformers#7]
Once again, thank you Phil for the amazing work and time you put into your work. I appreciate it! Two questions though:

1. Do I understand correctly that the keys and values that are passed from the encoder output to every layer of the decoder is nothing else but one single entity/tensor of shape (batch_size, num_tokens, dim_embedding) and it is only inside of the decoder layers that this tensor is then split into a key and a value tensor by means of multiplications with respective learnable tensors? So there really is only one single tensor that is passed to the decoder as  opposed to many illustrations, cf. 

![transformer_decoding_2](https://user-images.githubusercontent.com/22954412/103464615-77983000-4d35-11eb-83dc-e137132915d4.gif)

The split is performed in every decoder layer anew, correct?

2. I am trying to understand the resemblance/analogy to classical convnets in which after several layers of convolutions and pooling one usually uses the embeddings with reduced spatial dimension but increased feature/channel dimension for some further downstream tasks, cf. VGG architecture.

Is this akin to the encoder part of the Vision Transformer? 
the output of the encoder are separate feature vectors for every token/image patch which seems to be different from the resulting embeddings of convnets...

3. Talking again about ViT, could a decoder be thought of as kind of an upsampling/generative counterpart (cf. GANs) of a downsampling part, i.e. the encoder? I try to relate encoder and decoder and their use cases to the more classical architectures in Deep Learning.

Thank you in advance!

**Comment by lucidrains** [comment]
@CDitzel Hi Carsten again :)

1. Yes, the diagram should have showed the orange and blue keys and values in the center as one tensor as you described. It is then projected into its own set of keys and values at each cross attention layer of the decoder.

2. Encoder is exactly the same as ViT. I think that was the point the authors were trying to make, that the simplest encoder out of NLP can best all the complicated vision architectures devised so far.

3. The decoder you can think of as an RNN, but revised into an attention block, where the masking controls the flow of attention and gives it a learned unidirectionality. So the closest architecture you would be familiar with is the age old Karpathy CNN -> RNN (LSTM) image to caption. The CNN is replaced with the encoder here, and the decoder takes the place of the RNN

**Comment by lucidrains** [comment]
3. It's more that the Decoder is generative, conditioned by the encoder output (but you can condition it on anything, that's part of the flexibility of working with attention networks)

**Comment by CDitzel** [comment]
thank you Phil!
