### ISSUE TITLE
Is it possible to use AutoregressiveWrapper in combination with ContinuousTransformerWrapper

### ISSUE THREAD

**Issue by wingedsheep** [lucidrains/x-transformers#72]
Can I combine the AutoregressiveWrapper with the ContinuousTransformerWrapper?
ignore_index and pad_value are scalars and should be tensors here I believe.

Should I create a custom ContinuousAutoregressiveWrapper for this? 

I'm trying to use it like this: 

```
model = AutoregressiveWrapper(ContinuousTransformerWrapper(
    max_seq_len=self.max_sequence_length,
    dim_in=self.vector_dimension,
    dim_out=self.vector_dimension,
    emb_dim=self.embedding_dimension,
    use_pos_emb=True,
    attn_layers=Decoder(
        dim=self.embedding_dimension,
        depth=self.depth,
        heads=self.heads,
        attn_dropout=self.dropout,
        ff_dropout=self.dropout,
        rotary_pos_emb=True
    )
),
    pad_value=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]           # For example
).to(utils.get_device())
```

**Comment by lucidrains** [comment]
@wingedsheep oh hey, what are you trying to implement? is this for the decision transformer paper?

**Comment by lucidrains** [comment]
the autoregressive wrapper automatically takes care of the cross entropy loss between adjacent tokens, and only works in the discrete setting

**Comment by wingedsheep** [comment]
@lucidrains I am trying to implement a music generation model in my [Music Generation Toolbox](https://github.com/wingedsheep/music-generation-toolbox) project, that first uses an auto-encoder to create encodings for beats. Then use those encodings in an auto-regressive transformer model.

For the [compound word transformer model](https://arxiv.org/abs/2101.02402) I created custom wrappers, but I was wondering if maybe I missed a way to do it with x-transformers :)

**Comment by lucidrains** [comment]
@wingedsheep ohh got it - so i think the tried and tested way of doing this would be to use a vector quantized autoencoder, and then you can convert your music to discrete 'tokens', whereby you can use the autoregressive class out of the box. for continuous embeddings though, i'm not sure how it could be done, or even what type of loss to use. however, i've heard that the decision transformers paper did it successfully, so i'll have to reread, and perhaps i can then code up a `ContinuousAutoregressiveWrapper` class, if it all makes sense

**Comment by wingedsheep** [comment]
Thanks for the help! I'll read the decision transformers paper too.

**Comment by lucidrains** [comment]
@wingedsheep oh speak of the devil! https://arxiv.org/abs/2112.05329 it looks like you can train a continuous transformer autoregressively with a simple MSE loss! i'll get this wrapper built this week before Friday :)

**Comment by wingedsheep** [comment]
So as I understand they also have a fixed network for creating feature vectors, which would be somewhat similar to what I want to do with the auto-encoder. 

Thanks a lot! I'm really excited to see what comes out of this idea. I will let you know about the result :)

**Comment by lucidrains** [comment]
@wingedsheep let me know if this works for you https://github.com/lucidrains/x-transformers/commit/e82f8ef878ffadf9cae6828c4d4a2a9b16c25cc7 (you may need to sandwich the continuous transformer in between the encoder and decoder in an `nn.Sequential`)

**Comment by lucidrains** [comment]
@wingedsheep this is quite exciting for me - i had no idea this was possible!

**Comment by wingedsheep** [comment]
@lucidrains That was fast, thanks for making time so quickly! I tried the new ContinuousAutoregressiveWrapper and it seems to be doing exactly what I needed. Now I need to do some testing and write code to convert the result back to MIDI and see if it actually learns something interesting.

**Comment by lucidrains** [comment]
very cool! the faceformer paper has some interesting twists on the ALiBi encoding too to make their deep net work. maybe you can draw some inspiration from their architecture if you get stuck

**Comment by wingedsheep** [comment]
It works! I trained a model on the midi of "Californication" converted to encodings by the auto-encoder, and it actually learns to generate the song :D I'm curious how it will do when trained on more data.

**Comment by lucidrains** [comment]
amazing! 🎉

**Comment by wingedsheep** [comment]
@lucidrains VideoGPT also uses a similar idea https://arxiv.org/pdf/2104.10157.pdf
