### ISSUE TITLE
Transformer Quality in Linear Time gate control unit and FLASH code

### ISSUE THREAD

**Issue by aoom** [lucidrains/x-transformers#76]
Transformer Quality in Linear Time

Weizhe Hua, Zihang Dai, Hanxiao Liu, Quoc V. Le
We revisit the design choices in Transformers, and propose methods to address their weaknesses in handling long sequences. First, we propose a simple layer named gated attention unit, which allows the use of a weaker single-head attention with minimal quality loss. We then propose a linear approximation method complementary to this new layer, which is accelerator-friendly and highly competitive in quality. The resulting model, named FLASH, matches the perplexity of improved Transformers over both short (512) and long (8K) context lengths, achieving training speedups of up to 4.9× on Wiki-40B and 12.1× on PG-19 for auto-regressive language modeling, and 4.8× on C4 for masked language modeling.
Subjects:	Machine Learning (cs.LG); Artificial Intelligence (cs.AI); Computation and Language (cs.CL); Neural and Evolutionary Computing (cs.NE)
Cite as:	arXiv:2202.10447 [cs.LG]
 	(or arXiv:2202.10447v1 [cs.LG] for this version)
 
https://doi.org/10.48550/arXiv.2202.10447

https://arxiv.org/abs/2202.10447

**Comment by lucidrains** [comment]
@aoom hey! so this paper combines a bunch of ideas into one, and probably wouldn't fit into this repository

could you fill out https://forms.gle/Dtrxc6CceHEcqS6X6 ?

**Comment by aoom** [comment]
> @aoom hey! so this paper combines a bunch of ideas into one, and probably wouldn't fit into this repository
> 
> could you fill out https://forms.gle/Dtrxc6CceHEcqS6X6 ?

Thank you for your reply. I also feel  can start a separate implementation   :)

**Comment by lucidrains** [comment]
@aoom started a new repo here https://github.com/lucidrains/FLASH-pytorch feel free to contribute :)

**Comment by lucidrains** [comment]
@aoom ok, it is done https://github.com/lucidrains/flash-pytorch

**Comment by aoom** [comment]
> @aoom ok, it is done https://github.com/lucidrains/flash-pytorch

Thank you very much for your contribution, it was very beneficial. Thanks again！
