### ISSUE TITLE
Potential decoder+rotary embeddings bug

### ISSUE THREAD

**Issue by neonbjb** [lucidrains/x-transformers#80]
I think there is a subtle bug in this codebase that will only rear its head when performing autoregressive decoding on a model with rotary embeddings:

When decoding such a model, each iteration will progressively increase the sequence length of the `x` input to `AttentionLayers`, starting at 1. `AttentionLayers` computes the `max_rotary_emb_length` based on the length of `x`. This represents a divergence between inference and training which likely results in suboptimal performance on the first few decoder passes.

Since rotary embeddings are pretty flexible, I think the simple solution to this is to fix them to some expected number early in the decoding process. I have PR which implements this here: https://github.com/lucidrains/x-transformers/compare/main...neonbjb:patch-2

**Comment by lucidrains** [comment]
@neonbjb oh hey James, i don't really see a problem. i tested it on a length of 1024 tokens, and got a `max_rotary_emb_length` of 1024, and when i lowered that down to 1, i got 1. what values are you expecting?

**Comment by neonbjb** [comment]
I'll use my use-case to try and explain:

I'm building a Text To Speech model with rotary embeddings providing position information. [Here ](https://github.com/neonbjb/DL-Art-School/blob/master/codes/models/audio/tts/autoregressive_codegen2.py#L159) is the model definition (though you probably don't need to look at it to understand what is going on).

This is a classic encoder/decoder style transformer. During training, the decoder predicts the next token, but it is always fed a full sequence of tokens. For this reason `max_rotary_emb_length` is always in the range of ~100 during training.

During inference, I perform decoding by sampling one token at a time (which is fairly standard). The problem with this is that in the first sampling step, `max_rotary_emb_length`=1, in the second step, it is 2, then 3, etc. These cases were never encountered during training, and I am thinking this might pose a problem.

Digging into the implementation of RotaryEmbeddings more makes me less certain, though. It might be that these embeddings behave the same regardless of the value of `max_rotary_emb_length` and that parameter only allows them to attend to further distances.

I am going to close this for now and do some testing once my model is fully trained. I'll report back with results with and without these proposed changes.

**Comment by lucidrains** [comment]
@neonbjb hey James, if you are worried about extrapolating to positions not seen during training, try this feature instead https://github.com/lucidrains/x-transformers#dynamic-positional-bias
