### ISSUE TITLE
PaLM has never reported that SwishGLU shows better results than GEGLU.

### ISSUE THREAD

**Issue by KisuYang** [lucidrains/x-transformers#91]
Your description is as follows:

> The [PaLM](https://ai.googleblog.com/2022/04/pathways-language-model-palm-scaling-to.html) language model also reported even better results than GEGLU using the Swish GLU variant. You can turn this on by setting two flags.

"GEGLU" has to be "ReLU, GeLU or Swish"

**Comment by lucidrains** [comment]
@KisuYang ohh yes, you are correct https://github.com/lucidrains/x-transformers/commit/0a8fc9b3b0833e9add058c7984a4e080ce367c23

now i'm wondering why they chose to use that instead of geglu :thinking:
