### ISSUE TITLE
Implement/Integrate Flash-Attention

### ISSUE THREAD

**Issue by danieltudosiu** [lucidrains/x-transformers#97]
Hi Lucidrains,

I have stumbled across this paper that might be of interest to you.

Given how transformers are memory/compute hungry I think this will be highly useful for the repo.

Here is the reference: https://arxiv.org/abs/2205.14135

Here is the repo: https://github.com/HazyResearch/flash-attention

Cheers!

Dan

**Comment by lucidrains** [comment]
Hi Petru-Daniel

Yes indeed, it looks like a breakthrough moment

I've been playing around with it [here](https://github.com/lucidrains/memory-efficient-attention-pytorch/blob/main/memory_efficient_attention_pytorch/flash_attention.py) and [here](https://github.com/lucidrains/flash-attention-jax) and it works as advertised

I'll probably wait for Tri to whittle away a few more issues before I start using it for all my new transformers projects

In particular, it still lacks the ability to take in attention biases, and support for causal masking when the query and key / value lengths differ

**Comment by lucidrains** [comment]
One thing for sure, I owe Markus Rabe and Tri Dao dinner here in San Francisco :laughing:

**Comment by bitdom8** [comment]
Hi @lucidrains any update?
